syntax = "proto3";

import "PrimitivesWrappers.proto";
import "AdvancedBlocking.proto";
import "URLFilter.proto";

/* Service handles Advanced blocking page */
service AdvancedBlockingService {
    /* Get AdvancedBlocking settings  */
    rpc GetAdvancedBlocking(EmptyValue) returns (AdvancedBlocking);
    /* Update AdvancedBlocking */
    rpc UpdateAdvancedBlocking(AdvancedBlocking) returns (EmptyValue);
    /* Update RealTimeFiltersUpdate setting */
    rpc UpdateRealTimeFiltersUpdate(BoolValue) returns (EmptyValue);
    /* Get URLFilter state */
    rpc GetURLFilterState(EmptyValue) returns (URLFilterState);
    /* Mark URLFilter installation as requested */
    rpc MarkURLFilterInstallRequested(EmptyValue) returns (EmptyValue);
    /* Reset URLFilter prefilter cache */
    rpc ResetURLFilterCache(EmptyValue) returns (EmptyValue);
    /* Remove URLFilter configuration */
    rpc RemoveURLFilter(EmptyValue) returns (EmptyValue);
    /* Update URLFilter configuration */
    rpc UpdateURLFilterConfiguration(URLFilterConfiguration) returns (EmptyValue);
}
