syntax = "proto3";

option optimize_for = CODE_SIZE;

// AppStore subscription type
enum AppStoreSubscription {
    AppStoreSubscription_monthly = 0;
    AppStoreSubscription_annual = 1;
}

// Describes AppStore Subscription
message AppStoreSubscriptionInfo {
    string display_price = 1;
    int32 trial_days = 2;
    optional string intro_offer_display_price = 3;
}

// Additional promo info
message PromoInfo {
    string title = 1;
    string subtitle = 2;
    optional string button_text = 3;
    optional string button_url = 4;
}

// AppStore subscriptions error
enum AppStoreSubscriptionsError {
    AppStoreSubscriptionsError_unknown = 0;
    AppStoreSubscriptionsError_products_banned = 1;
    AppStoreSubscriptionsError_other_error = 2;
}

// AppStore available subscriptions
message AppStoreSubscriptions {
    AppStoreSubscriptionInfo monthly = 1;
    AppStoreSubscriptionInfo annual = 2;
    optional PromoInfo promoInfo = 3;
}

// Defines AppStore subscriptions message
message AppStoreSubscriptionsMessage {
    AppStoreSubscriptionsError error = 1;
    optional AppStoreSubscriptions result = 2;
}
