syntax = "proto3";

import "PrimitivesWrappers.proto";
import "URLFilter.proto";
import "Helpers.proto";

/* Service handles Advanced blocking page */
service AdvancedBlockingService {
    /* Get AdvancedRules */
    rpc GetAdvancedRules(EmptyValue) returns (BoolValue);
    /* Update AdvancedRules */
    rpc UpdateAdvancedRules(BoolValue) returns (EmptyValue);
     /* Get AdguardExtra */
    rpc GetAdguardExtra(EmptyValue) returns (BoolValue);
    /* Update AdguardExtra */
    rpc UpdateAdguardExtra(BoolValue) returns (EmptyValue);
     /* Get MailProtection */
    rpc GetMailProtection(EmptyValue) returns (BoolValue);
    /* Update MailProtection */
    rpc UpdateMailProtection(BoolValue) returns (EmptyValue);
     /* Get RealTimeFiltersUpdate */
    rpc GetRealTimeFiltersUpdate(EmptyValue) returns (BoolValue);
    /* Update RealTimeFiltersUpdate */
    rpc UpdateRealTimeFiltersUpdate(BoolValue) returns (EmptyValue);
    /* Get URLFilter state */
    rpc GetURLFilterState(EmptyValue) returns (URLFilterState);
    /* Set URLFilter enabled state */
    rpc SetURLFilterEnabled(BoolValue) returns (OptionalError);
    /* Update URLFilter protection level */
    rpc UpdateURLFilterProtectionLevel(URLFilterProtectionLevelUpdate) returns (OptionalError);
    /* Reset URLFilter prefilter cache */
    rpc ResetURLFilterCache(EmptyValue) returns (OptionalError);
    /* Remove URLFilter configuration */
    rpc RemoveURLFilter(EmptyValue) returns (OptionalError);
    /* Get URLFilter seen */
    rpc GetURLFilterSeen(EmptyValue) returns (BoolValue);
    /* Update URLFilterSeen state */
    rpc UpdateURLFilterSeen(BoolValue) returns (EmptyValue);
}
