/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: AdvancedBlocking.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class AdvancedBlocking extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        advancedRules?: boolean;
        adguardExtra?: boolean;
        mailProtectionEnabled?: boolean;
        realTimeFiltersUpdate?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("advancedRules" in data && data.advancedRules != undefined) {
                this.advancedRules = data.advancedRules;
            }
            if ("adguardExtra" in data && data.adguardExtra != undefined) {
                this.adguardExtra = data.adguardExtra;
            }
            if ("mailProtectionEnabled" in data && data.mailProtectionEnabled != undefined) {
                this.mailProtectionEnabled = data.mailProtectionEnabled;
            }
            if ("realTimeFiltersUpdate" in data && data.realTimeFiltersUpdate != undefined) {
                this.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
            }
        }
    }
    get advancedRules() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set advancedRules(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get adguardExtra() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set adguardExtra(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    get mailProtectionEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set mailProtectionEnabled(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get realTimeFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set realTimeFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        advancedRules?: boolean;
        adguardExtra?: boolean;
        mailProtectionEnabled?: boolean;
        realTimeFiltersUpdate?: boolean;
    }): AdvancedBlocking {
        const message = new AdvancedBlocking({});
        if (data.advancedRules != null) {
            message.advancedRules = data.advancedRules;
        }
        if (data.adguardExtra != null) {
            message.adguardExtra = data.adguardExtra;
        }
        if (data.mailProtectionEnabled != null) {
            message.mailProtectionEnabled = data.mailProtectionEnabled;
        }
        if (data.realTimeFiltersUpdate != null) {
            message.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
        }
        return message;
    }
    toObject() {
        const data: {
            advancedRules?: boolean;
            adguardExtra?: boolean;
            mailProtectionEnabled?: boolean;
            realTimeFiltersUpdate?: boolean;
        } = {};
        if (this.advancedRules != null) {
            data.advancedRules = this.advancedRules;
        }
        if (this.adguardExtra != null) {
            data.adguardExtra = this.adguardExtra;
        }
        if (this.mailProtectionEnabled != null) {
            data.mailProtectionEnabled = this.mailProtectionEnabled;
        }
        if (this.realTimeFiltersUpdate != null) {
            data.realTimeFiltersUpdate = this.realTimeFiltersUpdate;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.advancedRules != false)
            writer.writeBool(1, this.advancedRules);
        if (this.adguardExtra != false)
            writer.writeBool(2, this.adguardExtra);
        if (this.mailProtectionEnabled != false)
            writer.writeBool(3, this.mailProtectionEnabled);
        if (this.realTimeFiltersUpdate != false)
            writer.writeBool(4, this.realTimeFiltersUpdate);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AdvancedBlocking {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AdvancedBlocking();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.advancedRules = reader.readBool();
                    break;
                case 2:
                    message.adguardExtra = reader.readBool();
                    break;
                case 3:
                    message.mailProtectionEnabled = reader.readBool();
                    break;
                case 4:
                    message.realTimeFiltersUpdate = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): AdvancedBlocking {
        return AdvancedBlocking.deserialize(bytes);
    }
}
