/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Common.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum Theme {
    unknown = 0,
    system = 1,
    light = 2,
    dark = 3
}
export enum QuitReaction {
    unknown = 0,
    ask = 1,
    quit = 2,
    keepRunning = 3
}
export enum ReleaseVariants {
    unknown = 0,
    MAS = 1,
    standAlone = 2
}
export enum SafariExtensionType {
    general = 0,
    privacy = 1,
    security = 2,
    social = 3,
    other = 4,
    custom = 5,
    adguard_for_safari = 6
}
export enum SafariExtensionStatus {
    unknown = 0,
    ok = 1,
    loading = 2,
    disabled = 3,
    limit_exceeded = 4,
    converter_error = 5,
    safari_error = 6
}
export class SafariExtension extends pb_1.Message {
    #one_of_decls: number[][] = [[6]];
    constructor(data?: any[] | ({
        id?: string;
        rulesEnabled?: number;
        rulesTotal?: number;
        status?: SafariExtensionStatus;
        isConsideredEnabled?: boolean;
    } & (({
        safariError?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("rulesEnabled" in data && data.rulesEnabled != undefined) {
                this.rulesEnabled = data.rulesEnabled;
            }
            if ("rulesTotal" in data && data.rulesTotal != undefined) {
                this.rulesTotal = data.rulesTotal;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("safariError" in data && data.safariError != undefined) {
                this.safariError = data.safariError;
            }
            if ("isConsideredEnabled" in data && data.isConsideredEnabled != undefined) {
                this.isConsideredEnabled = data.isConsideredEnabled;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get rulesEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set rulesEnabled(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get rulesTotal() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set rulesTotal(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 4, SafariExtensionStatus.unknown) as SafariExtensionStatus;
    }
    set status(value: SafariExtensionStatus) {
        pb_1.Message.setField(this, 4, value);
    }
    get safariError() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set safariError(value: string) {
        pb_1.Message.setOneofField(this, 6, this.#one_of_decls[0], value);
    }
    get has_safari_error() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get isConsideredEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
    }
    set isConsideredEnabled(value: boolean) {
        pb_1.Message.setField(this, 7, value);
    }
    get _safariError() {
        const cases: {
            [index: number]: "none" | "safariError";
        } = {
            0: "none",
            6: "safariError"
        };
        return cases[pb_1.Message.computeOneofCase(this, [6])];
    }
    static fromObject(data: {
        id?: string;
        rulesEnabled?: number;
        rulesTotal?: number;
        status?: SafariExtensionStatus;
        safariError?: string;
        isConsideredEnabled?: boolean;
    }): SafariExtension {
        const message = new SafariExtension({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.rulesEnabled != null) {
            message.rulesEnabled = data.rulesEnabled;
        }
        if (data.rulesTotal != null) {
            message.rulesTotal = data.rulesTotal;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.safariError != null) {
            message.safariError = data.safariError;
        }
        if (data.isConsideredEnabled != null) {
            message.isConsideredEnabled = data.isConsideredEnabled;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            rulesEnabled?: number;
            rulesTotal?: number;
            status?: SafariExtensionStatus;
            safariError?: string;
            isConsideredEnabled?: boolean;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.rulesEnabled != null) {
            data.rulesEnabled = this.rulesEnabled;
        }
        if (this.rulesTotal != null) {
            data.rulesTotal = this.rulesTotal;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.safariError != null) {
            data.safariError = this.safariError;
        }
        if (this.isConsideredEnabled != null) {
            data.isConsideredEnabled = this.isConsideredEnabled;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.rulesEnabled != 0)
            writer.writeInt32(2, this.rulesEnabled);
        if (this.rulesTotal != 0)
            writer.writeInt32(3, this.rulesTotal);
        if (this.status != SafariExtensionStatus.unknown)
            writer.writeEnum(4, this.status);
        if (this.has_safari_error)
            writer.writeString(6, this.safariError);
        if (this.isConsideredEnabled != false)
            writer.writeBool(7, this.isConsideredEnabled);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtension {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtension();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.rulesEnabled = reader.readInt32();
                    break;
                case 3:
                    message.rulesTotal = reader.readInt32();
                    break;
                case 4:
                    message.status = reader.readEnum();
                    break;
                case 6:
                    message.safariError = reader.readString();
                    break;
                case 7:
                    message.isConsideredEnabled = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtension {
        return SafariExtension.deserialize(bytes);
    }
}
export class SafariExtensions extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        general?: SafariExtension;
        privacy?: SafariExtension;
        social?: SafariExtension;
        security?: SafariExtension;
        other?: SafariExtension;
        custom?: SafariExtension;
        adguardForSafari?: SafariExtension;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("general" in data && data.general != undefined) {
                this.general = data.general;
            }
            if ("privacy" in data && data.privacy != undefined) {
                this.privacy = data.privacy;
            }
            if ("social" in data && data.social != undefined) {
                this.social = data.social;
            }
            if ("security" in data && data.security != undefined) {
                this.security = data.security;
            }
            if ("other" in data && data.other != undefined) {
                this.other = data.other;
            }
            if ("custom" in data && data.custom != undefined) {
                this.custom = data.custom;
            }
            if ("adguardForSafari" in data && data.adguardForSafari != undefined) {
                this.adguardForSafari = data.adguardForSafari;
            }
        }
    }
    get general() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 1) as SafariExtension;
    }
    set general(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_general() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get privacy() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 2) as SafariExtension;
    }
    set privacy(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_privacy() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get social() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 3) as SafariExtension;
    }
    set social(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_social() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get security() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 4) as SafariExtension;
    }
    set security(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_security() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get other() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 5) as SafariExtension;
    }
    set other(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 5, value);
    }
    get has_other() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get custom() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 6) as SafariExtension;
    }
    set custom(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 6, value);
    }
    get has_custom() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get adguardForSafari() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 7) as SafariExtension;
    }
    set adguardForSafari(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 7, value);
    }
    get has_adguard_for_safari() {
        return pb_1.Message.getField(this, 7) != null;
    }
    static fromObject(data: {
        general?: ReturnType<typeof SafariExtension.prototype.toObject>;
        privacy?: ReturnType<typeof SafariExtension.prototype.toObject>;
        social?: ReturnType<typeof SafariExtension.prototype.toObject>;
        security?: ReturnType<typeof SafariExtension.prototype.toObject>;
        other?: ReturnType<typeof SafariExtension.prototype.toObject>;
        custom?: ReturnType<typeof SafariExtension.prototype.toObject>;
        adguardForSafari?: ReturnType<typeof SafariExtension.prototype.toObject>;
    }): SafariExtensions {
        const message = new SafariExtensions({});
        if (data.general != null) {
            message.general = SafariExtension.fromObject(data.general);
        }
        if (data.privacy != null) {
            message.privacy = SafariExtension.fromObject(data.privacy);
        }
        if (data.social != null) {
            message.social = SafariExtension.fromObject(data.social);
        }
        if (data.security != null) {
            message.security = SafariExtension.fromObject(data.security);
        }
        if (data.other != null) {
            message.other = SafariExtension.fromObject(data.other);
        }
        if (data.custom != null) {
            message.custom = SafariExtension.fromObject(data.custom);
        }
        if (data.adguardForSafari != null) {
            message.adguardForSafari = SafariExtension.fromObject(data.adguardForSafari);
        }
        return message;
    }
    toObject() {
        const data: {
            general?: ReturnType<typeof SafariExtension.prototype.toObject>;
            privacy?: ReturnType<typeof SafariExtension.prototype.toObject>;
            social?: ReturnType<typeof SafariExtension.prototype.toObject>;
            security?: ReturnType<typeof SafariExtension.prototype.toObject>;
            other?: ReturnType<typeof SafariExtension.prototype.toObject>;
            custom?: ReturnType<typeof SafariExtension.prototype.toObject>;
            adguardForSafari?: ReturnType<typeof SafariExtension.prototype.toObject>;
        } = {};
        if (this.general != null) {
            data.general = this.general.toObject();
        }
        if (this.privacy != null) {
            data.privacy = this.privacy.toObject();
        }
        if (this.social != null) {
            data.social = this.social.toObject();
        }
        if (this.security != null) {
            data.security = this.security.toObject();
        }
        if (this.other != null) {
            data.other = this.other.toObject();
        }
        if (this.custom != null) {
            data.custom = this.custom.toObject();
        }
        if (this.adguardForSafari != null) {
            data.adguardForSafari = this.adguardForSafari.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_general)
            writer.writeMessage(1, this.general, () => this.general.serialize(writer));
        if (this.has_privacy)
            writer.writeMessage(2, this.privacy, () => this.privacy.serialize(writer));
        if (this.has_social)
            writer.writeMessage(3, this.social, () => this.social.serialize(writer));
        if (this.has_security)
            writer.writeMessage(4, this.security, () => this.security.serialize(writer));
        if (this.has_other)
            writer.writeMessage(5, this.other, () => this.other.serialize(writer));
        if (this.has_custom)
            writer.writeMessage(6, this.custom, () => this.custom.serialize(writer));
        if (this.has_adguard_for_safari)
            writer.writeMessage(7, this.adguardForSafari, () => this.adguardForSafari.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtensions {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtensions();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.general, () => message.general = SafariExtension.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.privacy, () => message.privacy = SafariExtension.deserialize(reader));
                    break;
                case 3:
                    reader.readMessage(message.social, () => message.social = SafariExtension.deserialize(reader));
                    break;
                case 4:
                    reader.readMessage(message.security, () => message.security = SafariExtension.deserialize(reader));
                    break;
                case 5:
                    reader.readMessage(message.other, () => message.other = SafariExtension.deserialize(reader));
                    break;
                case 6:
                    reader.readMessage(message.custom, () => message.custom = SafariExtension.deserialize(reader));
                    break;
                case 7:
                    reader.readMessage(message.adguardForSafari, () => message.adguardForSafari = SafariExtension.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtensions {
        return SafariExtensions.deserialize(bytes);
    }
}
export class SafariExtensionUpdate extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        type?: SafariExtensionType;
        state?: SafariExtension;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
            if ("state" in data && data.state != undefined) {
                this.state = data.state;
            }
        }
    }
    get type() {
        return pb_1.Message.getFieldWithDefault(this, 1, SafariExtensionType.general) as SafariExtensionType;
    }
    set type(value: SafariExtensionType) {
        pb_1.Message.setField(this, 1, value);
    }
    get state() {
        return pb_1.Message.getWrapperField(this, SafariExtension, 2) as SafariExtension;
    }
    set state(value: SafariExtension) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_state() {
        return pb_1.Message.getField(this, 2) != null;
    }
    static fromObject(data: {
        type?: SafariExtensionType;
        state?: ReturnType<typeof SafariExtension.prototype.toObject>;
    }): SafariExtensionUpdate {
        const message = new SafariExtensionUpdate({});
        if (data.type != null) {
            message.type = data.type;
        }
        if (data.state != null) {
            message.state = SafariExtension.fromObject(data.state);
        }
        return message;
    }
    toObject() {
        const data: {
            type?: SafariExtensionType;
            state?: ReturnType<typeof SafariExtension.prototype.toObject>;
        } = {};
        if (this.type != null) {
            data.type = this.type;
        }
        if (this.state != null) {
            data.state = this.state.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.type != SafariExtensionType.general)
            writer.writeEnum(1, this.type);
        if (this.has_state)
            writer.writeMessage(2, this.state, () => this.state.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SafariExtensionUpdate {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SafariExtensionUpdate();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.type = reader.readEnum();
                    break;
                case 2:
                    reader.readMessage(message.state, () => message.state = SafariExtension.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SafariExtensionUpdate {
        return SafariExtensionUpdate.deserialize(bytes);
    }
}
export class UpdateThemeMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        theme?: Theme;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
        }
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 1, Theme.unknown) as Theme;
    }
    set theme(value: Theme) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        theme?: Theme;
    }): UpdateThemeMessage {
        const message = new UpdateThemeMessage({});
        if (data.theme != null) {
            message.theme = data.theme;
        }
        return message;
    }
    toObject() {
        const data: {
            theme?: Theme;
        } = {};
        if (this.theme != null) {
            data.theme = this.theme;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.theme != Theme.unknown)
            writer.writeEnum(1, this.theme);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateThemeMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateThemeMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.theme = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateThemeMessage {
        return UpdateThemeMessage.deserialize(bytes);
    }
}
export class UserConsent extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        filtersIds?: number[];
    }): UserConsent {
        const message = new UserConsent({});
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            filtersIds?: number[];
        } = {};
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.filtersIds.length)
            writer.writePackedInt32(1, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserConsent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserConsent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserConsent {
        return UserConsent.deserialize(bytes);
    }
}
