/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Settings.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Common";
import * as pb_1 from "google-protobuf";
export enum ImportMode {
    unknown = 0,
    full = 1,
    withoutAnnoyance = 2,
    cancel = 3
}
export class WindowGeometry extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        x?: number;
        y?: number;
        width?: number;
        height?: number;
        monitor?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("x" in data && data.x != undefined) {
                this.x = data.x;
            }
            if ("y" in data && data.y != undefined) {
                this.y = data.y;
            }
            if ("width" in data && data.width != undefined) {
                this.width = data.width;
            }
            if ("height" in data && data.height != undefined) {
                this.height = data.height;
            }
            if ("monitor" in data && data.monitor != undefined) {
                this.monitor = data.monitor;
            }
        }
    }
    get x() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set x(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get y() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set y(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get width() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set width(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get height() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set height(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get monitor() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set monitor(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        x?: number;
        y?: number;
        width?: number;
        height?: number;
        monitor?: number;
    }): WindowGeometry {
        const message = new WindowGeometry({});
        if (data.x != null) {
            message.x = data.x;
        }
        if (data.y != null) {
            message.y = data.y;
        }
        if (data.width != null) {
            message.width = data.width;
        }
        if (data.height != null) {
            message.height = data.height;
        }
        if (data.monitor != null) {
            message.monitor = data.monitor;
        }
        return message;
    }
    toObject() {
        const data: {
            x?: number;
            y?: number;
            width?: number;
            height?: number;
            monitor?: number;
        } = {};
        if (this.x != null) {
            data.x = this.x;
        }
        if (this.y != null) {
            data.y = this.y;
        }
        if (this.width != null) {
            data.width = this.width;
        }
        if (this.height != null) {
            data.height = this.height;
        }
        if (this.monitor != null) {
            data.monitor = this.monitor;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.x != 0)
            writer.writeInt32(1, this.x);
        if (this.y != 0)
            writer.writeInt32(2, this.y);
        if (this.width != 0)
            writer.writeInt32(3, this.width);
        if (this.height != 0)
            writer.writeInt32(4, this.height);
        if (this.monitor != 0)
            writer.writeInt32(5, this.monitor);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WindowGeometry {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WindowGeometry();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.x = reader.readInt32();
                    break;
                case 2:
                    message.y = reader.readInt32();
                    break;
                case 3:
                    message.width = reader.readInt32();
                    break;
                case 4:
                    message.height = reader.readInt32();
                    break;
                case 5:
                    message.monitor = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): WindowGeometry {
        return WindowGeometry.deserialize(bytes);
    }
}
export class Settings extends pb_1.Message {
    #one_of_decls: number[][] = [[13]];
    constructor(data?: any[] | ({
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: dependency_1.QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: dependency_1.ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
        allowTelemetry?: boolean;
        theme?: dependency_1.Theme;
        showSafariToolbarBadge?: boolean;
        lastUpdateMoreSevenDays?: boolean;
    } & (({
        userRulesEditorGeometry?: WindowGeometry;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [9], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("launchOnStartup" in data && data.launchOnStartup != undefined) {
                this.launchOnStartup = data.launchOnStartup;
            }
            if ("showInMenuBar" in data && data.showInMenuBar != undefined) {
                this.showInMenuBar = data.showInMenuBar;
            }
            if ("hardwareAcceleration" in data && data.hardwareAcceleration != undefined) {
                this.hardwareAcceleration = data.hardwareAcceleration;
            }
            if ("autoFiltersUpdate" in data && data.autoFiltersUpdate != undefined) {
                this.autoFiltersUpdate = data.autoFiltersUpdate;
            }
            if ("realTimeFiltersUpdate" in data && data.realTimeFiltersUpdate != undefined) {
                this.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
            }
            if ("quitReaction" in data && data.quitReaction != undefined) {
                this.quitReaction = data.quitReaction;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("consentFiltersIds" in data && data.consentFiltersIds != undefined) {
                this.consentFiltersIds = data.consentFiltersIds;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
            if ("allowTelemetry" in data && data.allowTelemetry != undefined) {
                this.allowTelemetry = data.allowTelemetry;
            }
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
            if ("userRulesEditorGeometry" in data && data.userRulesEditorGeometry != undefined) {
                this.userRulesEditorGeometry = data.userRulesEditorGeometry;
            }
            if ("showSafariToolbarBadge" in data && data.showSafariToolbarBadge != undefined) {
                this.showSafariToolbarBadge = data.showSafariToolbarBadge;
            }
            if ("lastUpdateMoreSevenDays" in data && data.lastUpdateMoreSevenDays != undefined) {
                this.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
            }
        }
    }
    get launchOnStartup() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set launchOnStartup(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get showInMenuBar() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set showInMenuBar(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    get hardwareAcceleration() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set hardwareAcceleration(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get autoFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set autoFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    get realTimeFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    set realTimeFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    get quitReaction() {
        return pb_1.Message.getFieldWithDefault(this, 6, dependency_1.QuitReaction.unknown) as dependency_1.QuitReaction;
    }
    set quitReaction(value: dependency_1.QuitReaction) {
        pb_1.Message.setField(this, 6, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 7, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 8, dependency_1.ReleaseVariants.unknown) as dependency_1.ReleaseVariants;
    }
    set releaseVariant(value: dependency_1.ReleaseVariants) {
        pb_1.Message.setField(this, 8, value);
    }
    get consentFiltersIds() {
        return pb_1.Message.getFieldWithDefault(this, 9, []) as number[];
    }
    set consentFiltersIds(value: number[]) {
        pb_1.Message.setField(this, 9, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get allowTelemetry() {
        return pb_1.Message.getFieldWithDefault(this, 11, false) as boolean;
    }
    set allowTelemetry(value: boolean) {
        pb_1.Message.setField(this, 11, value);
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 12, dependency_1.Theme.unknown) as dependency_1.Theme;
    }
    set theme(value: dependency_1.Theme) {
        pb_1.Message.setField(this, 12, value);
    }
    get userRulesEditorGeometry() {
        return pb_1.Message.getWrapperField(this, WindowGeometry, 13) as WindowGeometry;
    }
    set userRulesEditorGeometry(value: WindowGeometry) {
        pb_1.Message.setOneofWrapperField(this, 13, this.#one_of_decls[0], value);
    }
    get has_user_rules_editor_geometry() {
        return pb_1.Message.getField(this, 13) != null;
    }
    get showSafariToolbarBadge() {
        return pb_1.Message.getFieldWithDefault(this, 14, false) as boolean;
    }
    set showSafariToolbarBadge(value: boolean) {
        pb_1.Message.setField(this, 14, value);
    }
    get lastUpdateMoreSevenDays() {
        return pb_1.Message.getFieldWithDefault(this, 15, false) as boolean;
    }
    set lastUpdateMoreSevenDays(value: boolean) {
        pb_1.Message.setField(this, 15, value);
    }
    get _userRulesEditorGeometry() {
        const cases: {
            [index: number]: "none" | "userRulesEditorGeometry";
        } = {
            0: "none",
            13: "userRulesEditorGeometry"
        };
        return cases[pb_1.Message.computeOneofCase(this, [13])];
    }
    static fromObject(data: {
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: dependency_1.QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: dependency_1.ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
        allowTelemetry?: boolean;
        theme?: dependency_1.Theme;
        userRulesEditorGeometry?: ReturnType<typeof WindowGeometry.prototype.toObject>;
        showSafariToolbarBadge?: boolean;
        lastUpdateMoreSevenDays?: boolean;
    }): Settings {
        const message = new Settings({});
        if (data.launchOnStartup != null) {
            message.launchOnStartup = data.launchOnStartup;
        }
        if (data.showInMenuBar != null) {
            message.showInMenuBar = data.showInMenuBar;
        }
        if (data.hardwareAcceleration != null) {
            message.hardwareAcceleration = data.hardwareAcceleration;
        }
        if (data.autoFiltersUpdate != null) {
            message.autoFiltersUpdate = data.autoFiltersUpdate;
        }
        if (data.realTimeFiltersUpdate != null) {
            message.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
        }
        if (data.quitReaction != null) {
            message.quitReaction = data.quitReaction;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.consentFiltersIds != null) {
            message.consentFiltersIds = data.consentFiltersIds;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        if (data.allowTelemetry != null) {
            message.allowTelemetry = data.allowTelemetry;
        }
        if (data.theme != null) {
            message.theme = data.theme;
        }
        if (data.userRulesEditorGeometry != null) {
            message.userRulesEditorGeometry = WindowGeometry.fromObject(data.userRulesEditorGeometry);
        }
        if (data.showSafariToolbarBadge != null) {
            message.showSafariToolbarBadge = data.showSafariToolbarBadge;
        }
        if (data.lastUpdateMoreSevenDays != null) {
            message.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
        }
        return message;
    }
    toObject() {
        const data: {
            launchOnStartup?: boolean;
            showInMenuBar?: boolean;
            hardwareAcceleration?: boolean;
            autoFiltersUpdate?: boolean;
            realTimeFiltersUpdate?: boolean;
            quitReaction?: dependency_1.QuitReaction;
            debugLogging?: boolean;
            releaseVariant?: dependency_1.ReleaseVariants;
            consentFiltersIds?: number[];
            language?: string;
            allowTelemetry?: boolean;
            theme?: dependency_1.Theme;
            userRulesEditorGeometry?: ReturnType<typeof WindowGeometry.prototype.toObject>;
            showSafariToolbarBadge?: boolean;
            lastUpdateMoreSevenDays?: boolean;
        } = {};
        if (this.launchOnStartup != null) {
            data.launchOnStartup = this.launchOnStartup;
        }
        if (this.showInMenuBar != null) {
            data.showInMenuBar = this.showInMenuBar;
        }
        if (this.hardwareAcceleration != null) {
            data.hardwareAcceleration = this.hardwareAcceleration;
        }
        if (this.autoFiltersUpdate != null) {
            data.autoFiltersUpdate = this.autoFiltersUpdate;
        }
        if (this.realTimeFiltersUpdate != null) {
            data.realTimeFiltersUpdate = this.realTimeFiltersUpdate;
        }
        if (this.quitReaction != null) {
            data.quitReaction = this.quitReaction;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.consentFiltersIds != null) {
            data.consentFiltersIds = this.consentFiltersIds;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        if (this.allowTelemetry != null) {
            data.allowTelemetry = this.allowTelemetry;
        }
        if (this.theme != null) {
            data.theme = this.theme;
        }
        if (this.userRulesEditorGeometry != null) {
            data.userRulesEditorGeometry = this.userRulesEditorGeometry.toObject();
        }
        if (this.showSafariToolbarBadge != null) {
            data.showSafariToolbarBadge = this.showSafariToolbarBadge;
        }
        if (this.lastUpdateMoreSevenDays != null) {
            data.lastUpdateMoreSevenDays = this.lastUpdateMoreSevenDays;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.launchOnStartup != false)
            writer.writeBool(1, this.launchOnStartup);
        if (this.showInMenuBar != false)
            writer.writeBool(2, this.showInMenuBar);
        if (this.hardwareAcceleration != false)
            writer.writeBool(3, this.hardwareAcceleration);
        if (this.autoFiltersUpdate != false)
            writer.writeBool(4, this.autoFiltersUpdate);
        if (this.realTimeFiltersUpdate != false)
            writer.writeBool(5, this.realTimeFiltersUpdate);
        if (this.quitReaction != dependency_1.QuitReaction.unknown)
            writer.writeEnum(6, this.quitReaction);
        if (this.debugLogging != false)
            writer.writeBool(7, this.debugLogging);
        if (this.releaseVariant != dependency_1.ReleaseVariants.unknown)
            writer.writeEnum(8, this.releaseVariant);
        if (this.consentFiltersIds.length)
            writer.writePackedInt32(9, this.consentFiltersIds);
        if (this.language.length)
            writer.writeString(10, this.language);
        if (this.allowTelemetry != false)
            writer.writeBool(11, this.allowTelemetry);
        if (this.theme != dependency_1.Theme.unknown)
            writer.writeEnum(12, this.theme);
        if (this.has_user_rules_editor_geometry)
            writer.writeMessage(13, this.userRulesEditorGeometry, () => this.userRulesEditorGeometry.serialize(writer));
        if (this.showSafariToolbarBadge != false)
            writer.writeBool(14, this.showSafariToolbarBadge);
        if (this.lastUpdateMoreSevenDays != false)
            writer.writeBool(15, this.lastUpdateMoreSevenDays);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Settings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Settings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.launchOnStartup = reader.readBool();
                    break;
                case 2:
                    message.showInMenuBar = reader.readBool();
                    break;
                case 3:
                    message.hardwareAcceleration = reader.readBool();
                    break;
                case 4:
                    message.autoFiltersUpdate = reader.readBool();
                    break;
                case 5:
                    message.realTimeFiltersUpdate = reader.readBool();
                    break;
                case 6:
                    message.quitReaction = reader.readEnum();
                    break;
                case 7:
                    message.debugLogging = reader.readBool();
                    break;
                case 8:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 9:
                    message.consentFiltersIds = reader.readPackedInt32();
                    break;
                case 10:
                    message.language = reader.readString();
                    break;
                case 11:
                    message.allowTelemetry = reader.readBool();
                    break;
                case 12:
                    message.theme = reader.readEnum();
                    break;
                case 13:
                    reader.readMessage(message.userRulesEditorGeometry, () => message.userRulesEditorGeometry = WindowGeometry.deserialize(reader));
                    break;
                case 14:
                    message.showSafariToolbarBadge = reader.readBool();
                    break;
                case 15:
                    message.lastUpdateMoreSevenDays = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Settings {
        return Settings.deserialize(bytes);
    }
}
export class ImportSettingsConfirmation extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        mode?: ImportMode;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("mode" in data && data.mode != undefined) {
                this.mode = data.mode;
            }
        }
    }
    get mode() {
        return pb_1.Message.getFieldWithDefault(this, 1, ImportMode.unknown) as ImportMode;
    }
    set mode(value: ImportMode) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        mode?: ImportMode;
    }): ImportSettingsConfirmation {
        const message = new ImportSettingsConfirmation({});
        if (data.mode != null) {
            message.mode = data.mode;
        }
        return message;
    }
    toObject() {
        const data: {
            mode?: ImportMode;
        } = {};
        if (this.mode != null) {
            data.mode = this.mode;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.mode != ImportMode.unknown)
            writer.writeEnum(1, this.mode);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportSettingsConfirmation {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportSettingsConfirmation();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.mode = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportSettingsConfirmation {
        return ImportSettingsConfirmation.deserialize(bytes);
    }
}
export class ImportStatus extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 2, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        success?: boolean;
        filtersIds?: number[];
    }): ImportStatus {
        const message = new ImportStatus({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            filtersIds?: number[];
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.filtersIds.length)
            writer.writePackedInt32(2, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportStatus {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportStatus();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportStatus {
        return ImportStatus.deserialize(bytes);
    }
}
export class UpdateQuitReactionMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        reaction?: dependency_1.QuitReaction;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("reaction" in data && data.reaction != undefined) {
                this.reaction = data.reaction;
            }
        }
    }
    get reaction() {
        return pb_1.Message.getFieldWithDefault(this, 1, dependency_1.QuitReaction.unknown) as dependency_1.QuitReaction;
    }
    set reaction(value: dependency_1.QuitReaction) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        reaction?: dependency_1.QuitReaction;
    }): UpdateQuitReactionMessage {
        const message = new UpdateQuitReactionMessage({});
        if (data.reaction != null) {
            message.reaction = data.reaction;
        }
        return message;
    }
    toObject() {
        const data: {
            reaction?: dependency_1.QuitReaction;
        } = {};
        if (this.reaction != null) {
            data.reaction = this.reaction;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.reaction != dependency_1.QuitReaction.unknown)
            writer.writeEnum(1, this.reaction);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateQuitReactionMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateQuitReactionMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.reaction = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateQuitReactionMessage {
        return UpdateQuitReactionMessage.deserialize(bytes);
    }
}
