/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Telemetry.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum ActiveABTest {
    unknown = 0,
    AG_51019_advanced_settings = 1
}
export enum ABTestOption {
    unknown = 0,
    option_a = 1,
    option_b = 2
}
export class TelemetryEvent extends pb_1.Message {
    #one_of_decls: number[][] = [[1, 2]];
    constructor(data?: any[] | ({} & (({
        pageView?: PageView;
        customEvent?: never;
    } | {
        pageView?: never;
        customEvent?: CustomTelemetryEvent;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("pageView" in data && data.pageView != undefined) {
                this.pageView = data.pageView;
            }
            if ("customEvent" in data && data.customEvent != undefined) {
                this.customEvent = data.customEvent;
            }
        }
    }
    get pageView() {
        return pb_1.Message.getWrapperField(this, PageView, 1) as PageView;
    }
    set pageView(value: PageView) {
        pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
    }
    get has_page_view() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get customEvent() {
        return pb_1.Message.getWrapperField(this, CustomTelemetryEvent, 2) as CustomTelemetryEvent;
    }
    set customEvent(value: CustomTelemetryEvent) {
        pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
    }
    get has_custom_event() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get kind() {
        const cases: {
            [index: number]: "none" | "pageView" | "customEvent";
        } = {
            0: "none",
            1: "pageView",
            2: "customEvent"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1, 2])];
    }
    static fromObject(data: {
        pageView?: ReturnType<typeof PageView.prototype.toObject>;
        customEvent?: ReturnType<typeof CustomTelemetryEvent.prototype.toObject>;
    }): TelemetryEvent {
        const message = new TelemetryEvent({});
        if (data.pageView != null) {
            message.pageView = PageView.fromObject(data.pageView);
        }
        if (data.customEvent != null) {
            message.customEvent = CustomTelemetryEvent.fromObject(data.customEvent);
        }
        return message;
    }
    toObject() {
        const data: {
            pageView?: ReturnType<typeof PageView.prototype.toObject>;
            customEvent?: ReturnType<typeof CustomTelemetryEvent.prototype.toObject>;
        } = {};
        if (this.pageView != null) {
            data.pageView = this.pageView.toObject();
        }
        if (this.customEvent != null) {
            data.customEvent = this.customEvent.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_page_view)
            writer.writeMessage(1, this.pageView, () => this.pageView.serialize(writer));
        if (this.has_custom_event)
            writer.writeMessage(2, this.customEvent, () => this.customEvent.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TelemetryEvent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TelemetryEvent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.pageView, () => message.pageView = PageView.deserialize(reader));
                    break;
                case 2:
                    reader.readMessage(message.customEvent, () => message.customEvent = CustomTelemetryEvent.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): TelemetryEvent {
        return TelemetryEvent.deserialize(bytes);
    }
}
export class PageView extends pb_1.Message {
    #one_of_decls: number[][] = [[2]];
    constructor(data?: any[] | ({
        name?: string;
    } & (({
        refName?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("refName" in data && data.refName != undefined) {
                this.refName = data.refName;
            }
        }
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get refName() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set refName(value: string) {
        pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
    }
    get has_ref_name() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get _refName() {
        const cases: {
            [index: number]: "none" | "refName";
        } = {
            0: "none",
            2: "refName"
        };
        return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
        name?: string;
        refName?: string;
    }): PageView {
        const message = new PageView({});
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.refName != null) {
            message.refName = data.refName;
        }
        return message;
    }
    toObject() {
        const data: {
            name?: string;
            refName?: string;
        } = {};
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.refName != null) {
            data.refName = this.refName;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.name.length)
            writer.writeString(1, this.name);
        if (this.has_ref_name)
            writer.writeString(2, this.refName);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PageView {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PageView();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.name = reader.readString();
                    break;
                case 2:
                    message.refName = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PageView {
        return PageView.deserialize(bytes);
    }
}
export class CustomTelemetryEvent extends pb_1.Message {
    #one_of_decls: number[][] = [[3], [4]];
    constructor(data?: any[] | ({
        name?: string;
        refName?: string;
    } & (({
        actionName?: string;
    }) | ({
        labelName?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("refName" in data && data.refName != undefined) {
                this.refName = data.refName;
            }
            if ("actionName" in data && data.actionName != undefined) {
                this.actionName = data.actionName;
            }
            if ("labelName" in data && data.labelName != undefined) {
                this.labelName = data.labelName;
            }
        }
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get refName() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set refName(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get actionName() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set actionName(value: string) {
        pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
    }
    get has_action_name() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get labelName() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set labelName(value: string) {
        pb_1.Message.setOneofField(this, 4, this.#one_of_decls[1], value);
    }
    get has_label_name() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get _actionName() {
        const cases: {
            [index: number]: "none" | "actionName";
        } = {
            0: "none",
            3: "actionName"
        };
        return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _labelName() {
        const cases: {
            [index: number]: "none" | "labelName";
        } = {
            0: "none",
            4: "labelName"
        };
        return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    static fromObject(data: {
        name?: string;
        refName?: string;
        actionName?: string;
        labelName?: string;
    }): CustomTelemetryEvent {
        const message = new CustomTelemetryEvent({});
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.refName != null) {
            message.refName = data.refName;
        }
        if (data.actionName != null) {
            message.actionName = data.actionName;
        }
        if (data.labelName != null) {
            message.labelName = data.labelName;
        }
        return message;
    }
    toObject() {
        const data: {
            name?: string;
            refName?: string;
            actionName?: string;
            labelName?: string;
        } = {};
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.refName != null) {
            data.refName = this.refName;
        }
        if (this.actionName != null) {
            data.actionName = this.actionName;
        }
        if (this.labelName != null) {
            data.labelName = this.labelName;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.name.length)
            writer.writeString(1, this.name);
        if (this.refName.length)
            writer.writeString(2, this.refName);
        if (this.has_action_name)
            writer.writeString(3, this.actionName);
        if (this.has_label_name)
            writer.writeString(4, this.labelName);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CustomTelemetryEvent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CustomTelemetryEvent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.name = reader.readString();
                    break;
                case 2:
                    message.refName = reader.readString();
                    break;
                case 3:
                    message.actionName = reader.readString();
                    break;
                case 4:
                    message.labelName = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CustomTelemetryEvent {
        return CustomTelemetryEvent.deserialize(bytes);
    }
}
export class ActiveABTests extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        activeTests?: ABTest[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("activeTests" in data && data.activeTests != undefined) {
                this.activeTests = data.activeTests;
            }
        }
    }
    get activeTests() {
        return pb_1.Message.getRepeatedWrapperField(this, ABTest, 1) as ABTest[];
    }
    set activeTests(value: ABTest[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        activeTests?: ReturnType<typeof ABTest.prototype.toObject>[];
    }): ActiveABTests {
        const message = new ActiveABTests({});
        if (data.activeTests != null) {
            message.activeTests = data.activeTests.map(item => ABTest.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            activeTests?: ReturnType<typeof ABTest.prototype.toObject>[];
        } = {};
        if (this.activeTests != null) {
            data.activeTests = this.activeTests.map((item: ABTest) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.activeTests.length)
            writer.writeRepeatedMessage(1, this.activeTests, (item: ABTest) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ActiveABTests {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ActiveABTests();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.activeTests, () => pb_1.Message.addToRepeatedWrapperField(message, 1, ABTest.deserialize(reader), ABTest));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ActiveABTests {
        return ActiveABTests.deserialize(bytes);
    }
}
export class ABTest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        name?: ActiveABTest;
        option?: ABTestOption;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("option" in data && data.option != undefined) {
                this.option = data.option;
            }
        }
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 1, ActiveABTest.unknown) as ActiveABTest;
    }
    set name(value: ActiveABTest) {
        pb_1.Message.setField(this, 1, value);
    }
    get option() {
        return pb_1.Message.getFieldWithDefault(this, 2, ABTestOption.unknown) as ABTestOption;
    }
    set option(value: ABTestOption) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        name?: ActiveABTest;
        option?: ABTestOption;
    }): ABTest {
        const message = new ABTest({});
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.option != null) {
            message.option = data.option;
        }
        return message;
    }
    toObject() {
        const data: {
            name?: ActiveABTest;
            option?: ABTestOption;
        } = {};
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.option != null) {
            data.option = this.option;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.name != ActiveABTest.unknown)
            writer.writeEnum(1, this.name);
        if (this.option != ABTestOption.unknown)
            writer.writeEnum(2, this.option);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ABTest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ABTest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.name = reader.readEnum();
                    break;
                case 2:
                    message.option = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ABTest {
        return ABTest.deserialize(bytes);
    }
}
