/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Tray.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./Common";
import * as pb_1 from "google-protobuf";
export class GlobalSettings extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: dependency_1.ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        allowTelemetry?: boolean;
        theme?: dependency_1.Theme;
        lastFiltersUpdateTimestampMs?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("newVersionAvailable" in data && data.newVersionAvailable != undefined) {
                this.newVersionAvailable = data.newVersionAvailable;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("allowTelemetry" in data && data.allowTelemetry != undefined) {
                this.allowTelemetry = data.allowTelemetry;
            }
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
            if ("lastFiltersUpdateTimestampMs" in data && data.lastFiltersUpdateTimestampMs != undefined) {
                this.lastFiltersUpdateTimestampMs = data.lastFiltersUpdateTimestampMs;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get newVersionAvailable() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set newVersionAvailable(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 4, dependency_1.ReleaseVariants.unknown) as dependency_1.ReleaseVariants;
    }
    set releaseVariant(value: dependency_1.ReleaseVariants) {
        pb_1.Message.setField(this, 4, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 6, value);
    }
    get allowTelemetry() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    set allowTelemetry(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 9, dependency_1.Theme.unknown) as dependency_1.Theme;
    }
    set theme(value: dependency_1.Theme) {
        pb_1.Message.setField(this, 9, value);
    }
    get lastFiltersUpdateTimestampMs() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
    }
    set lastFiltersUpdateTimestampMs(value: number) {
        pb_1.Message.setField(this, 10, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: dependency_1.ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        allowTelemetry?: boolean;
        theme?: dependency_1.Theme;
        lastFiltersUpdateTimestampMs?: number;
    }): GlobalSettings {
        const message = new GlobalSettings({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.newVersionAvailable != null) {
            message.newVersionAvailable = data.newVersionAvailable;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.allowTelemetry != null) {
            message.allowTelemetry = data.allowTelemetry;
        }
        if (data.theme != null) {
            message.theme = data.theme;
        }
        if (data.lastFiltersUpdateTimestampMs != null) {
            message.lastFiltersUpdateTimestampMs = data.lastFiltersUpdateTimestampMs;
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            newVersionAvailable?: boolean;
            releaseVariant?: dependency_1.ReleaseVariants;
            language?: string;
            debugLogging?: boolean;
            allowTelemetry?: boolean;
            theme?: dependency_1.Theme;
            lastFiltersUpdateTimestampMs?: number;
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.newVersionAvailable != null) {
            data.newVersionAvailable = this.newVersionAvailable;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.allowTelemetry != null) {
            data.allowTelemetry = this.allowTelemetry;
        }
        if (this.theme != null) {
            data.theme = this.theme;
        }
        if (this.lastFiltersUpdateTimestampMs != null) {
            data.lastFiltersUpdateTimestampMs = this.lastFiltersUpdateTimestampMs;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.newVersionAvailable != false)
            writer.writeBool(3, this.newVersionAvailable);
        if (this.releaseVariant != dependency_1.ReleaseVariants.unknown)
            writer.writeEnum(4, this.releaseVariant);
        if (this.language.length)
            writer.writeString(5, this.language);
        if (this.debugLogging != false)
            writer.writeBool(6, this.debugLogging);
        if (this.allowTelemetry != false)
            writer.writeBool(8, this.allowTelemetry);
        if (this.theme != dependency_1.Theme.unknown)
            writer.writeEnum(9, this.theme);
        if (this.lastFiltersUpdateTimestampMs != 0)
            writer.writeInt64(10, this.lastFiltersUpdateTimestampMs);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GlobalSettings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GlobalSettings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 3:
                    message.newVersionAvailable = reader.readBool();
                    break;
                case 4:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 5:
                    message.language = reader.readString();
                    break;
                case 6:
                    message.debugLogging = reader.readBool();
                    break;
                case 8:
                    message.allowTelemetry = reader.readBool();
                    break;
                case 9:
                    message.theme = reader.readEnum();
                    break;
                case 10:
                    message.lastFiltersUpdateTimestampMs = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GlobalSettings {
        return GlobalSettings.deserialize(bytes);
    }
}
