/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: URLFilter.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum URLFilterStatus {
    unknown = 0,
    disabled = 1,
    invalid = 2,
    stopped = 3,
    starting = 4,
    running = 5,
    stopping = 6
}
export enum URLFilterProtectionLevel {
    essential = 0,
    safe = 1,
    family = 2
}
export class URLFilterConfiguration extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        protectionLevel?: URLFilterProtectionLevel;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("protectionLevel" in data && data.protectionLevel != undefined) {
                this.protectionLevel = data.protectionLevel;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get protectionLevel() {
        return pb_1.Message.getFieldWithDefault(this, 2, URLFilterProtectionLevel.essential) as URLFilterProtectionLevel;
    }
    set protectionLevel(value: URLFilterProtectionLevel) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        protectionLevel?: URLFilterProtectionLevel;
    }): URLFilterConfiguration {
        const message = new URLFilterConfiguration({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.protectionLevel != null) {
            message.protectionLevel = data.protectionLevel;
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            protectionLevel?: URLFilterProtectionLevel;
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.protectionLevel != null) {
            data.protectionLevel = this.protectionLevel;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.protectionLevel != URLFilterProtectionLevel.essential)
            writer.writeEnum(2, this.protectionLevel);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterConfiguration {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterConfiguration();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 2:
                    message.protectionLevel = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterConfiguration {
        return URLFilterConfiguration.deserialize(bytes);
    }
}
export class URLFilterInfo extends pb_1.Message {
    #one_of_decls: number[][] = [[1], [2]];
    constructor(data?: any[] | ({
        isInstalling?: boolean;
    } & (({
        rulesCount?: number;
    }) | ({
        lastUpdate?: number;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rulesCount" in data && data.rulesCount != undefined) {
                this.rulesCount = data.rulesCount;
            }
            if ("lastUpdate" in data && data.lastUpdate != undefined) {
                this.lastUpdate = data.lastUpdate;
            }
            if ("isInstalling" in data && data.isInstalling != undefined) {
                this.isInstalling = data.isInstalling;
            }
        }
    }
    get rulesCount() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set rulesCount(value: number) {
        pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_rules_count() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get lastUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set lastUpdate(value: number) {
        pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
    }
    get has_last_update() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get isInstalling() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set isInstalling(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get _rulesCount() {
        const cases: {
            [index: number]: "none" | "rulesCount";
        } = {
            0: "none",
            1: "rulesCount"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    get _lastUpdate() {
        const cases: {
            [index: number]: "none" | "lastUpdate";
        } = {
            0: "none",
            2: "lastUpdate"
        };
        return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
        rulesCount?: number;
        lastUpdate?: number;
        isInstalling?: boolean;
    }): URLFilterInfo {
        const message = new URLFilterInfo({});
        if (data.rulesCount != null) {
            message.rulesCount = data.rulesCount;
        }
        if (data.lastUpdate != null) {
            message.lastUpdate = data.lastUpdate;
        }
        if (data.isInstalling != null) {
            message.isInstalling = data.isInstalling;
        }
        return message;
    }
    toObject() {
        const data: {
            rulesCount?: number;
            lastUpdate?: number;
            isInstalling?: boolean;
        } = {};
        if (this.rulesCount != null) {
            data.rulesCount = this.rulesCount;
        }
        if (this.lastUpdate != null) {
            data.lastUpdate = this.lastUpdate;
        }
        if (this.isInstalling != null) {
            data.isInstalling = this.isInstalling;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_rules_count)
            writer.writeUint32(1, this.rulesCount);
        if (this.has_last_update)
            writer.writeInt64(2, this.lastUpdate);
        if (this.isInstalling != false)
            writer.writeBool(3, this.isInstalling);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.rulesCount = reader.readUint32();
                    break;
                case 2:
                    message.lastUpdate = reader.readInt64();
                    break;
                case 3:
                    message.isInstalling = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterInfo {
        return URLFilterInfo.deserialize(bytes);
    }
}
export class URLFilterState extends pb_1.Message {
    #one_of_decls: number[][] = [[4]];
    constructor(data?: any[] | ({
        status?: URLFilterStatus;
        configuration?: URLFilterConfiguration;
        info?: URLFilterInfo;
    } & (({
        errorMessage?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("configuration" in data && data.configuration != undefined) {
                this.configuration = data.configuration;
            }
            if ("info" in data && data.info != undefined) {
                this.info = data.info;
            }
            if ("errorMessage" in data && data.errorMessage != undefined) {
                this.errorMessage = data.errorMessage;
            }
        }
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 1, URLFilterStatus.unknown) as URLFilterStatus;
    }
    set status(value: URLFilterStatus) {
        pb_1.Message.setField(this, 1, value);
    }
    get configuration() {
        return pb_1.Message.getWrapperField(this, URLFilterConfiguration, 2) as URLFilterConfiguration;
    }
    set configuration(value: URLFilterConfiguration) {
        pb_1.Message.setWrapperField(this, 2, value);
    }
    get has_configuration() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get info() {
        return pb_1.Message.getWrapperField(this, URLFilterInfo, 3) as URLFilterInfo;
    }
    set info(value: URLFilterInfo) {
        pb_1.Message.setWrapperField(this, 3, value);
    }
    get has_info() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get errorMessage() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set errorMessage(value: string) {
        pb_1.Message.setOneofField(this, 4, this.#one_of_decls[0], value);
    }
    get has_error_message() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get _errorMessage() {
        const cases: {
            [index: number]: "none" | "errorMessage";
        } = {
            0: "none",
            4: "errorMessage"
        };
        return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    static fromObject(data: {
        status?: URLFilterStatus;
        configuration?: ReturnType<typeof URLFilterConfiguration.prototype.toObject>;
        info?: ReturnType<typeof URLFilterInfo.prototype.toObject>;
        errorMessage?: string;
    }): URLFilterState {
        const message = new URLFilterState({});
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.configuration != null) {
            message.configuration = URLFilterConfiguration.fromObject(data.configuration);
        }
        if (data.info != null) {
            message.info = URLFilterInfo.fromObject(data.info);
        }
        if (data.errorMessage != null) {
            message.errorMessage = data.errorMessage;
        }
        return message;
    }
    toObject() {
        const data: {
            status?: URLFilterStatus;
            configuration?: ReturnType<typeof URLFilterConfiguration.prototype.toObject>;
            info?: ReturnType<typeof URLFilterInfo.prototype.toObject>;
            errorMessage?: string;
        } = {};
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.configuration != null) {
            data.configuration = this.configuration.toObject();
        }
        if (this.info != null) {
            data.info = this.info.toObject();
        }
        if (this.errorMessage != null) {
            data.errorMessage = this.errorMessage;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.status != URLFilterStatus.unknown)
            writer.writeEnum(1, this.status);
        if (this.has_configuration)
            writer.writeMessage(2, this.configuration, () => this.configuration.serialize(writer));
        if (this.has_info)
            writer.writeMessage(3, this.info, () => this.info.serialize(writer));
        if (this.has_error_message)
            writer.writeString(4, this.errorMessage);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterState {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterState();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.status = reader.readEnum();
                    break;
                case 2:
                    reader.readMessage(message.configuration, () => message.configuration = URLFilterConfiguration.deserialize(reader));
                    break;
                case 3:
                    reader.readMessage(message.info, () => message.info = URLFilterInfo.deserialize(reader));
                    break;
                case 4:
                    message.errorMessage = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterState {
        return URLFilterState.deserialize(bytes);
    }
}
export class URLFilterProtectionLevelValue extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        value?: URLFilterProtectionLevel;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("value" in data && data.value != undefined) {
                this.value = data.value;
            }
        }
    }
    get value() {
        return pb_1.Message.getFieldWithDefault(this, 1, URLFilterProtectionLevel.essential) as URLFilterProtectionLevel;
    }
    set value(value: URLFilterProtectionLevel) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        value?: URLFilterProtectionLevel;
    }): URLFilterProtectionLevelValue {
        const message = new URLFilterProtectionLevelValue({});
        if (data.value != null) {
            message.value = data.value;
        }
        return message;
    }
    toObject() {
        const data: {
            value?: URLFilterProtectionLevel;
        } = {};
        if (this.value != null) {
            data.value = this.value;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.value != URLFilterProtectionLevel.essential)
            writer.writeEnum(1, this.value);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterProtectionLevelValue {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterProtectionLevelValue();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.value = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterProtectionLevelValue {
        return URLFilterProtectionLevelValue.deserialize(bytes);
    }
}
