# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

require 'pathname'
require 'tmpdir'

import 'Updating/Updating'
import 'Sciter'

ensure_bundle_exec

before_all do |lane, options|
  # Prepend bin/ to PATH so toolchain wrappers are used
  project_bin = File.expand_path('../bin', __dir__)
  ENV['PATH'] = "#{project_bin}:#{ENV['PATH']}"

  @config = options[:config] || ENV['CONFIGURATION']

  @root_path = File.dirname(File.realpath(__dir__))
  @project_file = "#{@root_path}/AdguardMini/AdguardMini.xcodeproj"

  DefaultUpdateConstants.root_path = @root_path
  DefaultUpdateConstants.project_path = @project_file
end

ENV['FASTLANE_PROC'] = 'true'
