/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Helpers.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class Path extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        path?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("path" in data && data.path != undefined) {
                this.path = data.path;
            }
        }
    }
    get path() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set path(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        path?: string;
    }): Path {
        const message = new Path({});
        if (data.path != null) {
            message.path = data.path;
        }
        return message;
    }
    toObject() {
        const data: {
            path?: string;
        } = {};
        if (this.path != null) {
            data.path = this.path;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.path.length)
            writer.writeString(1, this.path);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Path {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Path();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.path = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Path {
        return Path.deserialize(bytes);
    }
}
export class OptionalError extends pb_1.Message {
    #one_of_decls: number[][] = [[2]];
    constructor(data?: any[] | ({
        hasError?: boolean;
    } & (({
        message?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("hasError" in data && data.hasError != undefined) {
                this.hasError = data.hasError;
            }
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get hasError() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set hasError(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
    }
    get has_message() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get _message() {
        const cases: {
            [index: number]: "none" | "message";
        } = {
            0: "none",
            2: "message"
        };
        return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
        hasError?: boolean;
        message?: string;
    }): OptionalError {
        const message = new OptionalError({});
        if (data.hasError != null) {
            message.hasError = data.hasError;
        }
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            hasError?: boolean;
            message?: string;
        } = {};
        if (this.hasError != null) {
            data.hasError = this.hasError;
        }
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.hasError != false)
            writer.writeBool(1, this.hasError);
        if (this.has_message)
            writer.writeString(2, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OptionalError {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OptionalError();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.hasError = reader.readBool();
                    break;
                case 2:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): OptionalError {
        return OptionalError.deserialize(bytes);
    }
}
export class SelectFileParams extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        isSave?: boolean;
        title?: string;
        allowedExtensions?: string;
        initialPath?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("isSave" in data && data.isSave != undefined) {
                this.isSave = data.isSave;
            }
            if ("title" in data && data.title != undefined) {
                this.title = data.title;
            }
            if ("allowedExtensions" in data && data.allowedExtensions != undefined) {
                this.allowedExtensions = data.allowedExtensions;
            }
            if ("initialPath" in data && data.initialPath != undefined) {
                this.initialPath = data.initialPath;
            }
        }
    }
    get isSave() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set isSave(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get title() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set title(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get allowedExtensions() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set allowedExtensions(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get initialPath() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set initialPath(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        isSave?: boolean;
        title?: string;
        allowedExtensions?: string;
        initialPath?: string;
    }): SelectFileParams {
        const message = new SelectFileParams({});
        if (data.isSave != null) {
            message.isSave = data.isSave;
        }
        if (data.title != null) {
            message.title = data.title;
        }
        if (data.allowedExtensions != null) {
            message.allowedExtensions = data.allowedExtensions;
        }
        if (data.initialPath != null) {
            message.initialPath = data.initialPath;
        }
        return message;
    }
    toObject() {
        const data: {
            isSave?: boolean;
            title?: string;
            allowedExtensions?: string;
            initialPath?: string;
        } = {};
        if (this.isSave != null) {
            data.isSave = this.isSave;
        }
        if (this.title != null) {
            data.title = this.title;
        }
        if (this.allowedExtensions != null) {
            data.allowedExtensions = this.allowedExtensions;
        }
        if (this.initialPath != null) {
            data.initialPath = this.initialPath;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.isSave != false)
            writer.writeBool(1, this.isSave);
        if (this.title.length)
            writer.writeString(2, this.title);
        if (this.allowedExtensions.length)
            writer.writeString(3, this.allowedExtensions);
        if (this.initialPath.length)
            writer.writeString(4, this.initialPath);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SelectFileParams {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SelectFileParams();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.isSave = reader.readBool();
                    break;
                case 2:
                    message.title = reader.readString();
                    break;
                case 3:
                    message.allowedExtensions = reader.readString();
                    break;
                case 4:
                    message.initialPath = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SelectFileParams {
        return SelectFileParams.deserialize(bytes);
    }
}
export class SelectFilePath extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        path?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("path" in data && data.path != undefined) {
                this.path = data.path;
            }
        }
    }
    get path() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set path(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        path?: string;
    }): SelectFilePath {
        const message = new SelectFilePath({});
        if (data.path != null) {
            message.path = data.path;
        }
        return message;
    }
    toObject() {
        const data: {
            path?: string;
        } = {};
        if (this.path != null) {
            data.path = this.path;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.path.length)
            writer.writeString(1, this.path);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SelectFilePath {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SelectFilePath();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.path = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): SelectFilePath {
        return SelectFilePath.deserialize(bytes);
    }
}
