/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Settings.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum ReleaseVariants {
    unknown = 0,
    MAS = 1,
    standAlone = 2
}
export enum ImportMode {
    unknown = 0,
    full = 1,
    withoutAnnoyance = 2,
    cancel = 3
}
export enum QuitReaction {
    unknown = 0,
    ask = 1,
    quit = 2,
    keepRunning = 3
}
export enum Theme {
    unknown = 0,
    system = 1,
    light = 2,
    dark = 3
}
export class Settings extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
        allowTelemetry?: boolean;
        theme?: Theme;
        showSafariToolbarBadge?: boolean;
        lastUpdateMoreSevenDays?: boolean;
        mailProtectionEnabled?: boolean;
        loginItemEnabled?: boolean;
        non501User?: boolean;
        macos25OrLower?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [9], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("launchOnStartup" in data && data.launchOnStartup != undefined) {
                this.launchOnStartup = data.launchOnStartup;
            }
            if ("showInMenuBar" in data && data.showInMenuBar != undefined) {
                this.showInMenuBar = data.showInMenuBar;
            }
            if ("hardwareAcceleration" in data && data.hardwareAcceleration != undefined) {
                this.hardwareAcceleration = data.hardwareAcceleration;
            }
            if ("autoFiltersUpdate" in data && data.autoFiltersUpdate != undefined) {
                this.autoFiltersUpdate = data.autoFiltersUpdate;
            }
            if ("realTimeFiltersUpdate" in data && data.realTimeFiltersUpdate != undefined) {
                this.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
            }
            if ("quitReaction" in data && data.quitReaction != undefined) {
                this.quitReaction = data.quitReaction;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("consentFiltersIds" in data && data.consentFiltersIds != undefined) {
                this.consentFiltersIds = data.consentFiltersIds;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
            if ("allowTelemetry" in data && data.allowTelemetry != undefined) {
                this.allowTelemetry = data.allowTelemetry;
            }
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
            if ("showSafariToolbarBadge" in data && data.showSafariToolbarBadge != undefined) {
                this.showSafariToolbarBadge = data.showSafariToolbarBadge;
            }
            if ("lastUpdateMoreSevenDays" in data && data.lastUpdateMoreSevenDays != undefined) {
                this.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
            }
            if ("mailProtectionEnabled" in data && data.mailProtectionEnabled != undefined) {
                this.mailProtectionEnabled = data.mailProtectionEnabled;
            }
            if ("loginItemEnabled" in data && data.loginItemEnabled != undefined) {
                this.loginItemEnabled = data.loginItemEnabled;
            }
            if ("non501User" in data && data.non501User != undefined) {
                this.non501User = data.non501User;
            }
            if ("macos25OrLower" in data && data.macos25OrLower != undefined) {
                this.macos25OrLower = data.macos25OrLower;
            }
        }
    }
    get launchOnStartup() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set launchOnStartup(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get showInMenuBar() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set showInMenuBar(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    get hardwareAcceleration() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set hardwareAcceleration(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get autoFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
    }
    set autoFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 4, value);
    }
    get realTimeFiltersUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    set realTimeFiltersUpdate(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    get quitReaction() {
        return pb_1.Message.getFieldWithDefault(this, 6, QuitReaction.unknown) as QuitReaction;
    }
    set quitReaction(value: QuitReaction) {
        pb_1.Message.setField(this, 6, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 7, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 8, ReleaseVariants.unknown) as ReleaseVariants;
    }
    set releaseVariant(value: ReleaseVariants) {
        pb_1.Message.setField(this, 8, value);
    }
    get consentFiltersIds() {
        return pb_1.Message.getFieldWithDefault(this, 9, []) as number[];
    }
    set consentFiltersIds(value: number[]) {
        pb_1.Message.setField(this, 9, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get allowTelemetry() {
        return pb_1.Message.getFieldWithDefault(this, 11, false) as boolean;
    }
    set allowTelemetry(value: boolean) {
        pb_1.Message.setField(this, 11, value);
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 12, Theme.unknown) as Theme;
    }
    set theme(value: Theme) {
        pb_1.Message.setField(this, 12, value);
    }
    get showSafariToolbarBadge() {
        return pb_1.Message.getFieldWithDefault(this, 13, false) as boolean;
    }
    set showSafariToolbarBadge(value: boolean) {
        pb_1.Message.setField(this, 13, value);
    }
    get lastUpdateMoreSevenDays() {
        return pb_1.Message.getFieldWithDefault(this, 14, false) as boolean;
    }
    set lastUpdateMoreSevenDays(value: boolean) {
        pb_1.Message.setField(this, 14, value);
    }
    get mailProtectionEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 15, false) as boolean;
    }
    set mailProtectionEnabled(value: boolean) {
        pb_1.Message.setField(this, 15, value);
    }
    get loginItemEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 16, false) as boolean;
    }
    set loginItemEnabled(value: boolean) {
        pb_1.Message.setField(this, 16, value);
    }
    get non501User() {
        return pb_1.Message.getFieldWithDefault(this, 17, false) as boolean;
    }
    set non501User(value: boolean) {
        pb_1.Message.setField(this, 17, value);
    }
    get macos25OrLower() {
        return pb_1.Message.getFieldWithDefault(this, 18, false) as boolean;
    }
    set macos25OrLower(value: boolean) {
        pb_1.Message.setField(this, 18, value);
    }
    static fromObject(data: {
        launchOnStartup?: boolean;
        showInMenuBar?: boolean;
        hardwareAcceleration?: boolean;
        autoFiltersUpdate?: boolean;
        realTimeFiltersUpdate?: boolean;
        quitReaction?: QuitReaction;
        debugLogging?: boolean;
        releaseVariant?: ReleaseVariants;
        consentFiltersIds?: number[];
        language?: string;
        allowTelemetry?: boolean;
        theme?: Theme;
        showSafariToolbarBadge?: boolean;
        lastUpdateMoreSevenDays?: boolean;
        mailProtectionEnabled?: boolean;
        loginItemEnabled?: boolean;
        non501User?: boolean;
        macos25OrLower?: boolean;
    }): Settings {
        const message = new Settings({});
        if (data.launchOnStartup != null) {
            message.launchOnStartup = data.launchOnStartup;
        }
        if (data.showInMenuBar != null) {
            message.showInMenuBar = data.showInMenuBar;
        }
        if (data.hardwareAcceleration != null) {
            message.hardwareAcceleration = data.hardwareAcceleration;
        }
        if (data.autoFiltersUpdate != null) {
            message.autoFiltersUpdate = data.autoFiltersUpdate;
        }
        if (data.realTimeFiltersUpdate != null) {
            message.realTimeFiltersUpdate = data.realTimeFiltersUpdate;
        }
        if (data.quitReaction != null) {
            message.quitReaction = data.quitReaction;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.consentFiltersIds != null) {
            message.consentFiltersIds = data.consentFiltersIds;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        if (data.allowTelemetry != null) {
            message.allowTelemetry = data.allowTelemetry;
        }
        if (data.theme != null) {
            message.theme = data.theme;
        }
        if (data.showSafariToolbarBadge != null) {
            message.showSafariToolbarBadge = data.showSafariToolbarBadge;
        }
        if (data.lastUpdateMoreSevenDays != null) {
            message.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
        }
        if (data.mailProtectionEnabled != null) {
            message.mailProtectionEnabled = data.mailProtectionEnabled;
        }
        if (data.loginItemEnabled != null) {
            message.loginItemEnabled = data.loginItemEnabled;
        }
        if (data.non501User != null) {
            message.non501User = data.non501User;
        }
        if (data.macos25OrLower != null) {
            message.macos25OrLower = data.macos25OrLower;
        }
        return message;
    }
    toObject() {
        const data: {
            launchOnStartup?: boolean;
            showInMenuBar?: boolean;
            hardwareAcceleration?: boolean;
            autoFiltersUpdate?: boolean;
            realTimeFiltersUpdate?: boolean;
            quitReaction?: QuitReaction;
            debugLogging?: boolean;
            releaseVariant?: ReleaseVariants;
            consentFiltersIds?: number[];
            language?: string;
            allowTelemetry?: boolean;
            theme?: Theme;
            showSafariToolbarBadge?: boolean;
            lastUpdateMoreSevenDays?: boolean;
            mailProtectionEnabled?: boolean;
            loginItemEnabled?: boolean;
            non501User?: boolean;
            macos25OrLower?: boolean;
        } = {};
        if (this.launchOnStartup != null) {
            data.launchOnStartup = this.launchOnStartup;
        }
        if (this.showInMenuBar != null) {
            data.showInMenuBar = this.showInMenuBar;
        }
        if (this.hardwareAcceleration != null) {
            data.hardwareAcceleration = this.hardwareAcceleration;
        }
        if (this.autoFiltersUpdate != null) {
            data.autoFiltersUpdate = this.autoFiltersUpdate;
        }
        if (this.realTimeFiltersUpdate != null) {
            data.realTimeFiltersUpdate = this.realTimeFiltersUpdate;
        }
        if (this.quitReaction != null) {
            data.quitReaction = this.quitReaction;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.consentFiltersIds != null) {
            data.consentFiltersIds = this.consentFiltersIds;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        if (this.allowTelemetry != null) {
            data.allowTelemetry = this.allowTelemetry;
        }
        if (this.theme != null) {
            data.theme = this.theme;
        }
        if (this.showSafariToolbarBadge != null) {
            data.showSafariToolbarBadge = this.showSafariToolbarBadge;
        }
        if (this.lastUpdateMoreSevenDays != null) {
            data.lastUpdateMoreSevenDays = this.lastUpdateMoreSevenDays;
        }
        if (this.mailProtectionEnabled != null) {
            data.mailProtectionEnabled = this.mailProtectionEnabled;
        }
        if (this.loginItemEnabled != null) {
            data.loginItemEnabled = this.loginItemEnabled;
        }
        if (this.non501User != null) {
            data.non501User = this.non501User;
        }
        if (this.macos25OrLower != null) {
            data.macos25OrLower = this.macos25OrLower;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.launchOnStartup != false)
            writer.writeBool(1, this.launchOnStartup);
        if (this.showInMenuBar != false)
            writer.writeBool(2, this.showInMenuBar);
        if (this.hardwareAcceleration != false)
            writer.writeBool(3, this.hardwareAcceleration);
        if (this.autoFiltersUpdate != false)
            writer.writeBool(4, this.autoFiltersUpdate);
        if (this.realTimeFiltersUpdate != false)
            writer.writeBool(5, this.realTimeFiltersUpdate);
        if (this.quitReaction != QuitReaction.unknown)
            writer.writeEnum(6, this.quitReaction);
        if (this.debugLogging != false)
            writer.writeBool(7, this.debugLogging);
        if (this.releaseVariant != ReleaseVariants.unknown)
            writer.writeEnum(8, this.releaseVariant);
        if (this.consentFiltersIds.length)
            writer.writePackedInt32(9, this.consentFiltersIds);
        if (this.language.length)
            writer.writeString(10, this.language);
        if (this.allowTelemetry != false)
            writer.writeBool(11, this.allowTelemetry);
        if (this.theme != Theme.unknown)
            writer.writeEnum(12, this.theme);
        if (this.showSafariToolbarBadge != false)
            writer.writeBool(13, this.showSafariToolbarBadge);
        if (this.lastUpdateMoreSevenDays != false)
            writer.writeBool(14, this.lastUpdateMoreSevenDays);
        if (this.mailProtectionEnabled != false)
            writer.writeBool(15, this.mailProtectionEnabled);
        if (this.loginItemEnabled != false)
            writer.writeBool(16, this.loginItemEnabled);
        if (this.non501User != false)
            writer.writeBool(17, this.non501User);
        if (this.macos25OrLower != false)
            writer.writeBool(18, this.macos25OrLower);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Settings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Settings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.launchOnStartup = reader.readBool();
                    break;
                case 2:
                    message.showInMenuBar = reader.readBool();
                    break;
                case 3:
                    message.hardwareAcceleration = reader.readBool();
                    break;
                case 4:
                    message.autoFiltersUpdate = reader.readBool();
                    break;
                case 5:
                    message.realTimeFiltersUpdate = reader.readBool();
                    break;
                case 6:
                    message.quitReaction = reader.readEnum();
                    break;
                case 7:
                    message.debugLogging = reader.readBool();
                    break;
                case 8:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 9:
                    message.consentFiltersIds = reader.readPackedInt32();
                    break;
                case 10:
                    message.language = reader.readString();
                    break;
                case 11:
                    message.allowTelemetry = reader.readBool();
                    break;
                case 12:
                    message.theme = reader.readEnum();
                    break;
                case 13:
                    message.showSafariToolbarBadge = reader.readBool();
                    break;
                case 14:
                    message.lastUpdateMoreSevenDays = reader.readBool();
                    break;
                case 15:
                    message.mailProtectionEnabled = reader.readBool();
                    break;
                case 16:
                    message.loginItemEnabled = reader.readBool();
                    break;
                case 17:
                    message.non501User = reader.readBool();
                    break;
                case 18:
                    message.macos25OrLower = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Settings {
        return Settings.deserialize(bytes);
    }
}
export class UserConsent extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        filtersIds?: number[];
    }): UserConsent {
        const message = new UserConsent({});
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            filtersIds?: number[];
        } = {};
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.filtersIds.length)
            writer.writePackedInt32(1, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserConsent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserConsent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserConsent {
        return UserConsent.deserialize(bytes);
    }
}
export class ImportSettingsConfirmation extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        mode?: ImportMode;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("mode" in data && data.mode != undefined) {
                this.mode = data.mode;
            }
        }
    }
    get mode() {
        return pb_1.Message.getFieldWithDefault(this, 1, ImportMode.unknown) as ImportMode;
    }
    set mode(value: ImportMode) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        mode?: ImportMode;
    }): ImportSettingsConfirmation {
        const message = new ImportSettingsConfirmation({});
        if (data.mode != null) {
            message.mode = data.mode;
        }
        return message;
    }
    toObject() {
        const data: {
            mode?: ImportMode;
        } = {};
        if (this.mode != null) {
            data.mode = this.mode;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.mode != ImportMode.unknown)
            writer.writeEnum(1, this.mode);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportSettingsConfirmation {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportSettingsConfirmation();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.mode = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportSettingsConfirmation {
        return ImportSettingsConfirmation.deserialize(bytes);
    }
}
export class ImportStatus extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        success?: boolean;
        filtersIds?: number[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("success" in data && data.success != undefined) {
                this.success = data.success;
            }
            if ("filtersIds" in data && data.filtersIds != undefined) {
                this.filtersIds = data.filtersIds;
            }
        }
    }
    get success() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set success(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get filtersIds() {
        return pb_1.Message.getFieldWithDefault(this, 2, []) as number[];
    }
    set filtersIds(value: number[]) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        success?: boolean;
        filtersIds?: number[];
    }): ImportStatus {
        const message = new ImportStatus({});
        if (data.success != null) {
            message.success = data.success;
        }
        if (data.filtersIds != null) {
            message.filtersIds = data.filtersIds;
        }
        return message;
    }
    toObject() {
        const data: {
            success?: boolean;
            filtersIds?: number[];
        } = {};
        if (this.success != null) {
            data.success = this.success;
        }
        if (this.filtersIds != null) {
            data.filtersIds = this.filtersIds;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.success != false)
            writer.writeBool(1, this.success);
        if (this.filtersIds.length)
            writer.writePackedInt32(2, this.filtersIds);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ImportStatus {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ImportStatus();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.success = reader.readBool();
                    break;
                case 2:
                    message.filtersIds = reader.readPackedInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ImportStatus {
        return ImportStatus.deserialize(bytes);
    }
}
export class GlobalSettings extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        allowTelemetry?: boolean;
        theme?: Theme;
        lastFiltersUpdateTimestampMs?: number;
        hiddenStories?: string[];
        loginItemEnabled?: boolean;
        lastUpdateMoreSevenDays?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [11], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("newVersionAvailable" in data && data.newVersionAvailable != undefined) {
                this.newVersionAvailable = data.newVersionAvailable;
            }
            if ("releaseVariant" in data && data.releaseVariant != undefined) {
                this.releaseVariant = data.releaseVariant;
            }
            if ("language" in data && data.language != undefined) {
                this.language = data.language;
            }
            if ("debugLogging" in data && data.debugLogging != undefined) {
                this.debugLogging = data.debugLogging;
            }
            if ("allowTelemetry" in data && data.allowTelemetry != undefined) {
                this.allowTelemetry = data.allowTelemetry;
            }
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
            if ("lastFiltersUpdateTimestampMs" in data && data.lastFiltersUpdateTimestampMs != undefined) {
                this.lastFiltersUpdateTimestampMs = data.lastFiltersUpdateTimestampMs;
            }
            if ("hiddenStories" in data && data.hiddenStories != undefined) {
                this.hiddenStories = data.hiddenStories;
            }
            if ("loginItemEnabled" in data && data.loginItemEnabled != undefined) {
                this.loginItemEnabled = data.loginItemEnabled;
            }
            if ("lastUpdateMoreSevenDays" in data && data.lastUpdateMoreSevenDays != undefined) {
                this.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get newVersionAvailable() {
        return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
    }
    set newVersionAvailable(value: boolean) {
        pb_1.Message.setField(this, 3, value);
    }
    get releaseVariant() {
        return pb_1.Message.getFieldWithDefault(this, 4, ReleaseVariants.unknown) as ReleaseVariants;
    }
    set releaseVariant(value: ReleaseVariants) {
        pb_1.Message.setField(this, 4, value);
    }
    get language() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set language(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get debugLogging() {
        return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
    }
    set debugLogging(value: boolean) {
        pb_1.Message.setField(this, 6, value);
    }
    get allowTelemetry() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    set allowTelemetry(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 9, Theme.unknown) as Theme;
    }
    set theme(value: Theme) {
        pb_1.Message.setField(this, 9, value);
    }
    get lastFiltersUpdateTimestampMs() {
        return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
    }
    set lastFiltersUpdateTimestampMs(value: number) {
        pb_1.Message.setField(this, 10, value);
    }
    get hiddenStories() {
        return pb_1.Message.getFieldWithDefault(this, 11, []) as string[];
    }
    set hiddenStories(value: string[]) {
        pb_1.Message.setField(this, 11, value);
    }
    get loginItemEnabled() {
        return pb_1.Message.getFieldWithDefault(this, 12, false) as boolean;
    }
    set loginItemEnabled(value: boolean) {
        pb_1.Message.setField(this, 12, value);
    }
    get lastUpdateMoreSevenDays() {
        return pb_1.Message.getFieldWithDefault(this, 13, false) as boolean;
    }
    set lastUpdateMoreSevenDays(value: boolean) {
        pb_1.Message.setField(this, 13, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        newVersionAvailable?: boolean;
        releaseVariant?: ReleaseVariants;
        language?: string;
        debugLogging?: boolean;
        allowTelemetry?: boolean;
        theme?: Theme;
        lastFiltersUpdateTimestampMs?: number;
        hiddenStories?: string[];
        loginItemEnabled?: boolean;
        lastUpdateMoreSevenDays?: boolean;
    }): GlobalSettings {
        const message = new GlobalSettings({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.newVersionAvailable != null) {
            message.newVersionAvailable = data.newVersionAvailable;
        }
        if (data.releaseVariant != null) {
            message.releaseVariant = data.releaseVariant;
        }
        if (data.language != null) {
            message.language = data.language;
        }
        if (data.debugLogging != null) {
            message.debugLogging = data.debugLogging;
        }
        if (data.allowTelemetry != null) {
            message.allowTelemetry = data.allowTelemetry;
        }
        if (data.theme != null) {
            message.theme = data.theme;
        }
        if (data.lastFiltersUpdateTimestampMs != null) {
            message.lastFiltersUpdateTimestampMs = data.lastFiltersUpdateTimestampMs;
        }
        if (data.hiddenStories != null) {
            message.hiddenStories = data.hiddenStories;
        }
        if (data.loginItemEnabled != null) {
            message.loginItemEnabled = data.loginItemEnabled;
        }
        if (data.lastUpdateMoreSevenDays != null) {
            message.lastUpdateMoreSevenDays = data.lastUpdateMoreSevenDays;
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            newVersionAvailable?: boolean;
            releaseVariant?: ReleaseVariants;
            language?: string;
            debugLogging?: boolean;
            allowTelemetry?: boolean;
            theme?: Theme;
            lastFiltersUpdateTimestampMs?: number;
            hiddenStories?: string[];
            loginItemEnabled?: boolean;
            lastUpdateMoreSevenDays?: boolean;
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.newVersionAvailable != null) {
            data.newVersionAvailable = this.newVersionAvailable;
        }
        if (this.releaseVariant != null) {
            data.releaseVariant = this.releaseVariant;
        }
        if (this.language != null) {
            data.language = this.language;
        }
        if (this.debugLogging != null) {
            data.debugLogging = this.debugLogging;
        }
        if (this.allowTelemetry != null) {
            data.allowTelemetry = this.allowTelemetry;
        }
        if (this.theme != null) {
            data.theme = this.theme;
        }
        if (this.lastFiltersUpdateTimestampMs != null) {
            data.lastFiltersUpdateTimestampMs = this.lastFiltersUpdateTimestampMs;
        }
        if (this.hiddenStories != null) {
            data.hiddenStories = this.hiddenStories;
        }
        if (this.loginItemEnabled != null) {
            data.loginItemEnabled = this.loginItemEnabled;
        }
        if (this.lastUpdateMoreSevenDays != null) {
            data.lastUpdateMoreSevenDays = this.lastUpdateMoreSevenDays;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.newVersionAvailable != false)
            writer.writeBool(3, this.newVersionAvailable);
        if (this.releaseVariant != ReleaseVariants.unknown)
            writer.writeEnum(4, this.releaseVariant);
        if (this.language.length)
            writer.writeString(5, this.language);
        if (this.debugLogging != false)
            writer.writeBool(6, this.debugLogging);
        if (this.allowTelemetry != false)
            writer.writeBool(8, this.allowTelemetry);
        if (this.theme != Theme.unknown)
            writer.writeEnum(9, this.theme);
        if (this.lastFiltersUpdateTimestampMs != 0)
            writer.writeInt64(10, this.lastFiltersUpdateTimestampMs);
        if (this.hiddenStories.length)
            writer.writeRepeatedString(11, this.hiddenStories);
        if (this.loginItemEnabled != false)
            writer.writeBool(12, this.loginItemEnabled);
        if (this.lastUpdateMoreSevenDays != false)
            writer.writeBool(13, this.lastUpdateMoreSevenDays);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GlobalSettings {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GlobalSettings();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 3:
                    message.newVersionAvailable = reader.readBool();
                    break;
                case 4:
                    message.releaseVariant = reader.readEnum();
                    break;
                case 5:
                    message.language = reader.readString();
                    break;
                case 6:
                    message.debugLogging = reader.readBool();
                    break;
                case 8:
                    message.allowTelemetry = reader.readBool();
                    break;
                case 9:
                    message.theme = reader.readEnum();
                    break;
                case 10:
                    message.lastFiltersUpdateTimestampMs = reader.readInt64();
                    break;
                case 11:
                    pb_1.Message.addToRepeatedField(message, 11, reader.readString());
                    break;
                case 12:
                    message.loginItemEnabled = reader.readBool();
                    break;
                case 13:
                    message.lastUpdateMoreSevenDays = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GlobalSettings {
        return GlobalSettings.deserialize(bytes);
    }
}
export class UpdateQuitReactionMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        reaction?: QuitReaction;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("reaction" in data && data.reaction != undefined) {
                this.reaction = data.reaction;
            }
        }
    }
    get reaction() {
        return pb_1.Message.getFieldWithDefault(this, 1, QuitReaction.unknown) as QuitReaction;
    }
    set reaction(value: QuitReaction) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        reaction?: QuitReaction;
    }): UpdateQuitReactionMessage {
        const message = new UpdateQuitReactionMessage({});
        if (data.reaction != null) {
            message.reaction = data.reaction;
        }
        return message;
    }
    toObject() {
        const data: {
            reaction?: QuitReaction;
        } = {};
        if (this.reaction != null) {
            data.reaction = this.reaction;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.reaction != QuitReaction.unknown)
            writer.writeEnum(1, this.reaction);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateQuitReactionMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateQuitReactionMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.reaction = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateQuitReactionMessage {
        return UpdateQuitReactionMessage.deserialize(bytes);
    }
}
export class UpdateThemeMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        theme?: Theme;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("theme" in data && data.theme != undefined) {
                this.theme = data.theme;
            }
        }
    }
    get theme() {
        return pb_1.Message.getFieldWithDefault(this, 1, Theme.unknown) as Theme;
    }
    set theme(value: Theme) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        theme?: Theme;
    }): UpdateThemeMessage {
        const message = new UpdateThemeMessage({});
        if (data.theme != null) {
            message.theme = data.theme;
        }
        return message;
    }
    toObject() {
        const data: {
            theme?: Theme;
        } = {};
        if (this.theme != null) {
            data.theme = this.theme;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.theme != Theme.unknown)
            writer.writeEnum(1, this.theme);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateThemeMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateThemeMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.theme = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UpdateThemeMessage {
        return UpdateThemeMessage.deserialize(bytes);
    }
}
