/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: URLFilter.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum URLFilterStatus {
    unknown = 0,
    error = 1,
    loading = 2,
    running = 3
}
export enum URLFilterProtectionLevel {
    essential = 0,
    safe = 1,
    family = 2
}
export class URLFilterInfo extends pb_1.Message {
    #one_of_decls: number[][] = [[1], [2]];
    constructor(data?: any[] | ({} & (({
        rulesCount?: number;
    }) | ({
        lastUpdate?: number;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("rulesCount" in data && data.rulesCount != undefined) {
                this.rulesCount = data.rulesCount;
            }
            if ("lastUpdate" in data && data.lastUpdate != undefined) {
                this.lastUpdate = data.lastUpdate;
            }
        }
    }
    get rulesCount() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set rulesCount(value: number) {
        pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_rules_count() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get lastUpdate() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set lastUpdate(value: number) {
        pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
    }
    get has_last_update() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get _rulesCount() {
        const cases: {
            [index: number]: "none" | "rulesCount";
        } = {
            0: "none",
            1: "rulesCount"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    get _lastUpdate() {
        const cases: {
            [index: number]: "none" | "lastUpdate";
        } = {
            0: "none",
            2: "lastUpdate"
        };
        return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    static fromObject(data: {
        rulesCount?: number;
        lastUpdate?: number;
    }): URLFilterInfo {
        const message = new URLFilterInfo({});
        if (data.rulesCount != null) {
            message.rulesCount = data.rulesCount;
        }
        if (data.lastUpdate != null) {
            message.lastUpdate = data.lastUpdate;
        }
        return message;
    }
    toObject() {
        const data: {
            rulesCount?: number;
            lastUpdate?: number;
        } = {};
        if (this.rulesCount != null) {
            data.rulesCount = this.rulesCount;
        }
        if (this.lastUpdate != null) {
            data.lastUpdate = this.lastUpdate;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_rules_count)
            writer.writeUint32(1, this.rulesCount);
        if (this.has_last_update)
            writer.writeInt64(2, this.lastUpdate);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.rulesCount = reader.readUint32();
                    break;
                case 2:
                    message.lastUpdate = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterInfo {
        return URLFilterInfo.deserialize(bytes);
    }
}
export class URLFilterState extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        enabled?: boolean;
        protectionLevel?: URLFilterProtectionLevel;
        status?: URLFilterStatus;
        info?: URLFilterInfo;
        isInstalled?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("enabled" in data && data.enabled != undefined) {
                this.enabled = data.enabled;
            }
            if ("protectionLevel" in data && data.protectionLevel != undefined) {
                this.protectionLevel = data.protectionLevel;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("info" in data && data.info != undefined) {
                this.info = data.info;
            }
            if ("isInstalled" in data && data.isInstalled != undefined) {
                this.isInstalled = data.isInstalled;
            }
        }
    }
    get enabled() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set enabled(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    get protectionLevel() {
        return pb_1.Message.getFieldWithDefault(this, 2, URLFilterProtectionLevel.essential) as URLFilterProtectionLevel;
    }
    set protectionLevel(value: URLFilterProtectionLevel) {
        pb_1.Message.setField(this, 2, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 3, URLFilterStatus.unknown) as URLFilterStatus;
    }
    set status(value: URLFilterStatus) {
        pb_1.Message.setField(this, 3, value);
    }
    get info() {
        return pb_1.Message.getWrapperField(this, URLFilterInfo, 4) as URLFilterInfo;
    }
    set info(value: URLFilterInfo) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_info() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get isInstalled() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    set isInstalled(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        enabled?: boolean;
        protectionLevel?: URLFilterProtectionLevel;
        status?: URLFilterStatus;
        info?: ReturnType<typeof URLFilterInfo.prototype.toObject>;
        isInstalled?: boolean;
    }): URLFilterState {
        const message = new URLFilterState({});
        if (data.enabled != null) {
            message.enabled = data.enabled;
        }
        if (data.protectionLevel != null) {
            message.protectionLevel = data.protectionLevel;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.info != null) {
            message.info = URLFilterInfo.fromObject(data.info);
        }
        if (data.isInstalled != null) {
            message.isInstalled = data.isInstalled;
        }
        return message;
    }
    toObject() {
        const data: {
            enabled?: boolean;
            protectionLevel?: URLFilterProtectionLevel;
            status?: URLFilterStatus;
            info?: ReturnType<typeof URLFilterInfo.prototype.toObject>;
            isInstalled?: boolean;
        } = {};
        if (this.enabled != null) {
            data.enabled = this.enabled;
        }
        if (this.protectionLevel != null) {
            data.protectionLevel = this.protectionLevel;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.info != null) {
            data.info = this.info.toObject();
        }
        if (this.isInstalled != null) {
            data.isInstalled = this.isInstalled;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.enabled != false)
            writer.writeBool(1, this.enabled);
        if (this.protectionLevel != URLFilterProtectionLevel.essential)
            writer.writeEnum(2, this.protectionLevel);
        if (this.status != URLFilterStatus.unknown)
            writer.writeEnum(3, this.status);
        if (this.has_info)
            writer.writeMessage(4, this.info, () => this.info.serialize(writer));
        if (this.isInstalled != false)
            writer.writeBool(5, this.isInstalled);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterState {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterState();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.enabled = reader.readBool();
                    break;
                case 2:
                    message.protectionLevel = reader.readEnum();
                    break;
                case 3:
                    message.status = reader.readEnum();
                    break;
                case 4:
                    reader.readMessage(message.info, () => message.info = URLFilterInfo.deserialize(reader));
                    break;
                case 5:
                    message.isInstalled = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterState {
        return URLFilterState.deserialize(bytes);
    }
}
export class URLFilterProtectionLevelUpdate extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        protectionLevel?: URLFilterProtectionLevel;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("protectionLevel" in data && data.protectionLevel != undefined) {
                this.protectionLevel = data.protectionLevel;
            }
        }
    }
    get protectionLevel() {
        return pb_1.Message.getFieldWithDefault(this, 1, URLFilterProtectionLevel.essential) as URLFilterProtectionLevel;
    }
    set protectionLevel(value: URLFilterProtectionLevel) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        protectionLevel?: URLFilterProtectionLevel;
    }): URLFilterProtectionLevelUpdate {
        const message = new URLFilterProtectionLevelUpdate({});
        if (data.protectionLevel != null) {
            message.protectionLevel = data.protectionLevel;
        }
        return message;
    }
    toObject() {
        const data: {
            protectionLevel?: URLFilterProtectionLevel;
        } = {};
        if (this.protectionLevel != null) {
            data.protectionLevel = this.protectionLevel;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.protectionLevel != URLFilterProtectionLevel.essential)
            writer.writeEnum(1, this.protectionLevel);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): URLFilterProtectionLevelUpdate {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new URLFilterProtectionLevelUpdate();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.protectionLevel = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): URLFilterProtectionLevelUpdate {
        return URLFilterProtectionLevelUpdate.deserialize(bytes);
    }
}
