// SPDX-FileCopyrightText: AdGuard Software Limited
//
// SPDX-License-Identifier: GPL-3.0-or-later

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: URLFilter.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Derived, user-facing URL filter status. 
public enum URLFilterStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case error // = 1
  case loading // = 2
  case running // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .error
    case 2: self = .loading
    case 3: self = .running
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .error: return 1
    case .loading: return 2
    case .running: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [URLFilterStatus] = [
    .unknown,
    .error,
    .loading,
    .running,
  ]

}

/// Protection level applied to the URL filter. 
public enum URLFilterProtectionLevel: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case essential // = 0
  case safe // = 1
  case family // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .essential
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .essential
    case 1: self = .safe
    case 2: self = .family
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .essential: return 0
    case .safe: return 1
    case .family: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [URLFilterProtectionLevel] = [
    .essential,
    .safe,
    .family,
  ]

}

/// Read-only URL filter metadata. 
public struct URLFilterInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rulesCount: UInt32 {
    get {return _rulesCount ?? 0}
    set {_rulesCount = newValue}
  }
  /// Returns true if `rulesCount` has been explicitly set.
  public var hasRulesCount: Bool {return self._rulesCount != nil}
  /// Clears the value of `rulesCount`. Subsequent reads from it will return its default value.
  public mutating func clearRulesCount() {self._rulesCount = nil}

  public var lastUpdate: Int64 {
    get {return _lastUpdate ?? 0}
    set {_lastUpdate = newValue}
  }
  /// Returns true if `lastUpdate` has been explicitly set.
  public var hasLastUpdate: Bool {return self._lastUpdate != nil}
  /// Clears the value of `lastUpdate`. Subsequent reads from it will return its default value.
  public mutating func clearLastUpdate() {self._lastUpdate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rulesCount: UInt32? = nil
  fileprivate var _lastUpdate: Int64? = nil
}

/// Aggregate URL filter state exchanged with the UI. 
public struct URLFilterState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enabled: Bool = false

  public var protectionLevel: URLFilterProtectionLevel = .essential

  public var status: URLFilterStatus = .unknown

  public var info: URLFilterInfo {
    get {return _info ?? URLFilterInfo()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  public var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  public mutating func clearInfo() {self._info = nil}

  public var isInstalled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _info: URLFilterInfo? = nil
}

public struct URLFilterProtectionLevelUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var protectionLevel: URLFilterProtectionLevel = .essential

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension URLFilterStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0URLFilterStatus_unknown\0\u{1}URLFilterStatus_error\0\u{1}URLFilterStatus_loading\0\u{1}URLFilterStatus_running\0")
}

extension URLFilterProtectionLevel: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0URLFilterProtectionLevel_essential\0\u{1}URLFilterProtectionLevel_safe\0\u{1}URLFilterProtectionLevel_family\0")
}

extension URLFilterInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "URLFilterInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}rules_count\0\u{3}last_update\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._rulesCount) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self._lastUpdate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rulesCount {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastUpdate {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: URLFilterInfo, rhs: URLFilterInfo) -> Bool {
    if lhs._rulesCount != rhs._rulesCount {return false}
    if lhs._lastUpdate != rhs._lastUpdate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension URLFilterState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "URLFilterState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0\u{3}protection_level\0\u{1}status\0\u{1}info\0\u{3}is_installed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.protectionLevel) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._info) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isInstalled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.protectionLevel != .essential {
      try visitor.visitSingularEnumField(value: self.protectionLevel, fieldNumber: 2)
    }
    if self.status != .unknown {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 3)
    }
    try { if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.isInstalled != false {
      try visitor.visitSingularBoolField(value: self.isInstalled, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: URLFilterState, rhs: URLFilterState) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.protectionLevel != rhs.protectionLevel {return false}
    if lhs.status != rhs.status {return false}
    if lhs._info != rhs._info {return false}
    if lhs.isInstalled != rhs.isInstalled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension URLFilterProtectionLevelUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "URLFilterProtectionLevelUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protection_level\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.protectionLevel) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.protectionLevel != .essential {
      try visitor.visitSingularEnumField(value: self.protectionLevel, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: URLFilterProtectionLevelUpdate, rhs: URLFilterProtectionLevelUpdate) -> Bool {
    if lhs.protectionLevel != rhs.protectionLevel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
