// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Tray.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct GlobalSettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enabled: Bool = false

  public var newVersionAvailable: Bool = false

  public var releaseVariant: ReleaseVariants = .unknown

  public var language: String = String()

  public var debugLogging: Bool = false

  public var allowTelemetry: Bool = false

  public var theme: Theme = .unknown

  public var lastFiltersUpdateTimestampMs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension GlobalSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "GlobalSettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0\u{2}\u{2}newVersionAvailable\0\u{1}releaseVariant\0\u{1}language\0\u{3}debug_logging\0\u{4}\u{2}allow_telemetry\0\u{1}theme\0\u{3}last_filters_update_timestamp_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.newVersionAvailable) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.releaseVariant) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.language) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.debugLogging) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.allowTelemetry) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self.theme) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.lastFiltersUpdateTimestampMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if self.newVersionAvailable != false {
      try visitor.visitSingularBoolField(value: self.newVersionAvailable, fieldNumber: 3)
    }
    if self.releaseVariant != .unknown {
      try visitor.visitSingularEnumField(value: self.releaseVariant, fieldNumber: 4)
    }
    if !self.language.isEmpty {
      try visitor.visitSingularStringField(value: self.language, fieldNumber: 5)
    }
    if self.debugLogging != false {
      try visitor.visitSingularBoolField(value: self.debugLogging, fieldNumber: 6)
    }
    if self.allowTelemetry != false {
      try visitor.visitSingularBoolField(value: self.allowTelemetry, fieldNumber: 8)
    }
    if self.theme != .unknown {
      try visitor.visitSingularEnumField(value: self.theme, fieldNumber: 9)
    }
    if self.lastFiltersUpdateTimestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.lastFiltersUpdateTimestampMs, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: GlobalSettings, rhs: GlobalSettings) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.newVersionAvailable != rhs.newVersionAvailable {return false}
    if lhs.releaseVariant != rhs.releaseVariant {return false}
    if lhs.language != rhs.language {return false}
    if lhs.debugLogging != rhs.debugLogging {return false}
    if lhs.allowTelemetry != rhs.allowTelemetry {return false}
    if lhs.theme != rhs.theme {return false}
    if lhs.lastFiltersUpdateTimestampMs != rhs.lastFiltersUpdateTimestampMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
